### PR TITLE
build: update connect

### PR DESCRIPTION
**Pull request by hstove**
Updates connect to latest, and updates the `authOptions` to use `onFinish` and the default `authOrigin`.

### CODE REVIEW

**Comment by aulneau** [comment]
@hstove I just merged a PR, can you rebase off `master` with these changes before I review?

**Comment by hstove** [comment]
@aulneau yep, all set.

**Comment by aulneau** [comment]
@hstove I tried the preview link and there is something off with Connect:
Screen Shot 2020-07-22 at 7 36 19 PM

**Comment by hstove** [comment]
@aulneau cool, looks like the resolution fixed it. Weird issue.

Sometimes the way node/npm supports multiple versions of a dep is nice, and sometimes it can be a pain in the butt (like here). I remember "fun" times in Ruby trying to coerce my gems so that they'd be able to resolve to the same version of a dependency.

**Comment by aulneau** [comment]
@hstove there is still a bug here that once someone logs in, the connect modal does not dismiss. Could it be a regression in connect somewhere?

**Comment by markmhx** [comment]
@aulneau mind creating an issue in the UX repo with the problem you see and linking to here?

**Comment by agraebe** [comment]
updating this issue based on the sprint meeting: this should be based on the latest version (with stenciljs)

**Pull request closed without merging**
